// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using SalesManagement.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace SalesManagement.Data
{
    public partial class SalesmanagementContext
    {
        private SalesmanagementContextProcedures _procedures;

        public virtual SalesmanagementContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new SalesmanagementContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public SalesmanagementContextProcedures GetProcedures()
        {
            return Procedures;
        }

        protected void OnModelCreatingGeneratedProcedures(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<UserStoreResult>().HasNoKey().ToView(null);
        }
    }

    public interface ISalesmanagementContextProceduresContract
    {
        Task<List<UserStoreResult>> UserStoreAsync(int? user_id, CancellationToken cancellationToken = default);
    }

    public partial class SalesmanagementContextProcedures
    {
        private readonly SalesmanagementContext _context;

        public SalesmanagementContextProcedures(SalesmanagementContext context)
        {
            _context = context;
        }

        public virtual async Task<List<UserStoreResult>> UserStoreAsync(int? user_id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "user_id",
                    Value = user_id ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<UserStoreResult>("EXEC @returnValue = [dbo].[UserStore] @user_id", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
