// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SalesManagement.Models
{
    public partial class Order
    {
        public int OrderQuantity { get; set; }
        public int? InvoiceId { get; set; }
        public int? ProductId { get; set; }

        public virtual Invoice Invoice { get; set; }
        public virtual Product Product { get; set; }
    }
}