// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace SalesManagement.Models
{
    public partial class signInResult
    {
        public int user_id { get; set; }
        public string user_username { get; set; }
        public string user_password { get; set; }
    }
}
