// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace SalesManagement.Models
{
    public partial class StoreInvoicesResult
    {
        public int invoice_id { get; set; }
        public string invoice_client { get; set; }
        public DateTime? invoice_date { get; set; }
        public bool? invoice_is_paid { get; set; }
        public string invoice_address { get; set; }
        public int order_quantity { get; set; }
        public string product_name { get; set; }
        public int product_quantity { get; set; }
        public long product_price { get; set; }
    }
}
