// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace SalesManagement.Models
{
    public partial class UserStoreResult
    {
        public int store_id { get; set; }
        public string store_name { get; set; }
        public string store_address { get; set; }
    }
}
