// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SalesManagement.Models
{
    public partial class User
    {
        public User()
        {
            Stores = new HashSet<Store>();
        }

        public int UserId { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string phone { get; set; }

        public virtual ICollection<Store> Stores { get; set; }
    }
}